version: "3.3"

services:
  api_container:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile-api
    restart: unless-stopped
    command: node dist/main.js
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file: .env.prod
  nginx_container:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile-nginx
    restart: unless-stopped
    environment:
      APP_SERVER_NAME: ${APP_SERVER_NAME}
      APP_PREFIX: ${APP_PREFIX}
      APP_PORT: ${APP_PORT}
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    env_file: .env.prod
  redis_container:
    restart: unless-stopped
  postgres_container:
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file: .env.prod
  mailhog_container:
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - api_container
    command: certonly --webroot --webroot-path=/var/www/html --email juraj.markesic.dev@gmail.com --agree-tos --no-eff-email --staging -d primrose.agency  -d www.primrose.agency
volumes:
  pgdata: {}
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /var/www/API/dist2
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /var/www/API/dhparam/
      o: bind
    
