version: "3.3"

services:
  api_container:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile-api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 9229:9229
    command: npm run start:debug
    env_file: .env
  nginx_container:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile-nginx
    ports:
      - 80:80
      - 443:443
    environment:
      APP_SERVER_NAME: ${APP_SERVER_NAME}
      APP_PREFIX: ${APP_PREFIX}
      APP_PORT: ${APP_PORT}
  postgres_container:
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
  mailhog_container:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - api_network

