version: "3.3"

services:
  api_container:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile-api
    restart: always
    command: node dist/main.js
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file: .env.prod
  nginx_container:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile-nginx
    restart: always
    environment:
      APP_SERVER_NAME: ${APP_SERVER_NAME}
      APP_PREFIX: ${APP_PREFIX}
      APP_PORT: ${APP_PORT}
    env_file: .env.prod
  redis_container:
    restart: always
  postgres_container:
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file: .env.prod
  mailhog_container:
    restart: always
