version: "3.3"

services:
  api_container:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile-api
    restart: unless-stopped
    command: node dist/main.js
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file: .env.prod
  nginx_container:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile-nginx
    restart: unless-stopped
    environment:
      APP_SERVER_NAME: ${APP_SERVER_NAME}
      APP_PREFIX: ${APP_PREFIX}
      APP_PORT: ${APP_PORT}
    volumes:
      - certbot/conf:/etc/letsencrypt
      - certbot/www:/var/www/certbot
      - dhparam:/etc/ssl/certs
    env_file: .env.prod
  redis_container:
    restart: unless-stopped
  postgres_container:
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file: .env.prod
  mailhog_container:
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot/conf:/etc/letsencrypt
      - certbot/www:/var/www/certbot
    depends_on:
      - api_container
volumes:
  pgdata: {}
  certbot: 
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /var/www/API/dhparam/
      o: bind
    
