FROM node:12.13 AS builder
WORKDIR /app
COPY ./package.json ./
RUN npm install
COPY . .
RUN node --max-old-space-size=2200 $(which npm)  npm run build


FROM node:12.13-alpine
WORKDIR /app
COPY --from=builder /app ./
